### ISSUE TITLE
Use EIP-1967 for storage slots

### ISSUE THREAD

**Issue by satyamakgec** [maple-labs/proxy-factory#2]
Do we need to use EIP-1967 here 

https://github.com/maple-labs/proxy-factory/blob/b18909327abfb86857d81a382a2a9f75931a95ff/contracts/Proxy.sol#L11

Ref - https://eips.ethereum.org/EIPS/eip-1967
Although it says that this EIP is likely to change.

**Comment by deluca-mike** [comment]
Yup. That value is a placeholder until we agree on a standard. I prefer prefixing with the eventual ERC or EIP, rather than baking in some first-party properties, like "org.maple".

**Comment by lucas-manuel** [comment]
Lets verify on etherscan and see what is supported (we should also research if the testnet etherscans support proxies).

**Comment by deluca-mike** [comment]
Done
