### ISSUE TITLE
bug: Violating transparent proxy pattern

### ISSUE THREAD

**Issue by satyamakgec** [maple-labs/proxy-factory#3]
https://github.com/maple-labs/proxy-factory/blob/b18909327abfb86857d81a382a2a9f75931a95ff/contracts/Proxied.sol#L13

https://github.com/maple-labs/proxy-factory/blob/b18909327abfb86857d81a382a2a9f75931a95ff/contracts/Proxied.sol#L17

Both functions are violating the transparent proxy methodology. We don't need any other public function besides `migrate` which is also ACL-based.

**Comment by deluca-mike** [comment]
Not really a bug.

OZ `AdminUpgradeabilityProxy` already exposes:
```js
function admin() external view returns (address);
function implementation() external view returns (address);
function changeAdmin(address newAdmin) external;
function upgradeTo(address newImplementation) external;
function upgradeToAndCall(address newImplementation, bytes data) payable external;
```
which will consume 5 selectors no longer available, via the fallback, to the implementation.

Inheriting `Proxied` allows the the implementation to avoid erroneously using:
```js
function factory() public view returns (address _factory);
function implementation() external view returns (address);
function migrate(address migrator, bytes calldata arguments) external;
```
which are needed for upgradeable proxies in the currently designed fashion. Further, it allows the developers the ability to override, decorate (with ACL), and upgrade these methods, and removes any burden (especially bytecode) from the proxy, which is the code most deployed.

**Comment by lucas-manuel** [comment]
Since interfaces are not inherited by proxy, they are inherited by implementation, this is not an issue
