### ISSUE TITLE
logic: What is the use of the Proxied contract?

### ISSUE THREAD

**Issue by satyamakgec** [maple-labs/proxy-factory#5]
Shouldn't the `Proxied` inherit the Proxy contract to support of full proxy https://github.com/maple-labs/proxy-factory/blob/b18909327abfb86857d81a382a2a9f75931a95ff/contracts/Proxied.sol#L9 otherwise I don't understand the use of the `Proxied` contract.

**Comment by deluca-mike** [comment]
See https://github.com/maple-labs/proxy-factory/issues/3#issuecomment-912606605

tl;dr - Allows implementations to be explicitly aware of selectors consumed by the act of being proxied, and removes all such logic from the bytecode deployed per proxy instance.
