### ISSUE TITLE
discussion: `factory.getImplementation()` returning implementation for msg.sender

### ISSUE THREAD

**Issue by deluca-mike** [maple-labs/proxy-factory#6]
Current state `factory.getImplementation()` returns the implementation of the caller (`msg.sender`), in order to save gas and bytecode of the proxy. This feels a bit odd, since `factory.implementationFor(address proxy)` exists, and is more functional, but I can't quite put my finger on how to articulate why this helper function wrapping `implementationFor` feels weird.

We can, instead, have the proxy call `factory.implementationFor(address(this))`, which would result in a bit more bytecode and runtime gas for the proxy, but then we can get rid of `getImplementation()`.

Thoughts?

**Comment by lucas-manuel** [comment]
I vote for getting rid of `getImplementation`, I think `factory.implementationFor(address(this))` would be fine gas wise.

**Comment by lucas-manuel** [comment]
Agreed on making `implemenationFor` public function
